In [1]:
library(plot3D)
library(tidyr)
library(tidyverse)
library(scales)
library(latex2exp)
library(cowplot)
library(ggh4x)
library(ggpubr)
library(patchwork)

library(scales)
library(reticulate)
library(RColorBrewer)
library(stringr)
library(dplyr)
library(ggplot2)
library(gridExtra)

Warning message in fun(libname, pkgname):
“couldn't connect to display "/private/tmp/com.apple.launchd.KNVZdiQDdw/org.xquartz:0"”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ purrr     1.0.2
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.1     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ purrr::%||%()   masks base::%||%()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor



Attaching package: ‘cowplot’


The following object is masked from ‘package:lubridate’:

    stamp



Attaching package: ‘ggpubr’


The following object is masked from ‘package:cowplot’:

    get_legend



Attaching package: ‘patchwork’


The following object is masked from ‘package:cowplot’:

    align_plots



Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine

In [2]:
setwd(dirname(dirname(getwd())))
root_path <- getwd()

In [3]:
source("./MethodsEvaluation/results_processing_for_analysis.R")
source("./Pysindy/utils/pysindy_results_processing_for_analysis.R")
source("./ResultsAnalysis/plot-style/house_style.R")

In [4]:
nbfigsize <- function(width, height) {
    options(
        repr.plot.width = width,
        repr.plot.height = height,
        repr.plot.res = 300
    )
}

nbfigsize(
    width = 12,
    height = 11
)

## Generate the computational time table for ARGOS family methods

In [5]:
dynamical_system_name <- "lorenz"
experiment_name_list <- list("argos-alasso", "bayesian-alasso-ro")
method_list <- list("argos-alasso", "bayesian-alasso-ro")
function_number <- 3
exp_n <- TRUE
typical_pattern <- "snr49"
num_init <- 100

In [6]:
total_results_summary_df <- enhance_total_results_summary_df(
    root_path = root_path,
    experiment_name_list = experiment_name_list,
    method_list = method_list,
    function_number = function_number,
    num_init = num_init,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern
)
head(total_results_summary_df)

[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_1_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_1_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_1_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_2_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_2_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_2_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_3_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_3_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/lorenz/results/lorenz_3_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_1_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_1_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_1_e4_e5_se100_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_2_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_2_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_2_e4_e5_se100_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_3_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_3_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/lorenz/results/lorenz_3_e4_e5_se100_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

  run_id list_name eta function_id method num_of_identified_terms run_time
1 1.1.1  n=1e+2    2   1           alasso 1                       34.37162
2 1.1.2  n=1e+2    2   1           alasso 2                       36.39715
3 1.1.3  n=1e+2    2   1           alasso 0                       35.73503
4 1.1.4  n=1e+2    2   1           alasso 1                       33.13522
5 1.1.5  n=1e+2    2   1           alasso 0                       30.31232
6 1.1.6  n=1e+2    2   1           alasso 1                       33.25113
  function_indicator case_id n_running_id
1 xdot               1-2-1   2-1
2 xdot               1-2-2   2-2
3 xdot               1-2-3   2-3
4 xdot               1-2-4   2-4
5 xdot               1-2-5   2-5
6 xdot               1-2-6   2-6

In [7]:
methods_running_time_table <- create_time_complexity_table(
    total_results_summary_df = total_results_summary_df,
    type_1_method_list = c("alasso"),
    type_1_method_cpu_number = 20,
    type_2_method_list = c("bayesian-argos", "bayesian-alasso-ro"),
    type_2_method_cpu_number = 4
)
head(methods_running_time_table)

         n_running_id run_time eta method
alasso.1 2-1          1852.171 2   alasso
alasso.2 2-10         1690.542 2   alasso
alasso.3 2-100        1602.689 2   alasso
alasso.4 2-11         1695.187 2   alasso
alasso.5 2-12         1661.613 2   alasso
alasso.6 2-13         1698.561 2   alasso

## Generate the computational time table for SINDy methods

In [8]:
pysindy_path <- file.path(getwd(), "Pysindy")

In [9]:
total_results_summary_df_sindy <- enhance_total_results_summary_df_py(
    root_path = pysindy_path,
    experiment_name_list = c("pysindy"),
    method_list = c("pysindy"),
    num_init = num_init,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern
)

[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Pysindy/exp/lorenz/results/lorenz_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Pysindy/exp/lorenz/results/lorenz_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Pysindy/exp/lorenz/results/lorenz_e4_e5_se100_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

In [10]:
sindy_running_time_table <- create_time_complexity_table_py(
    total_results_summary_df = total_results_summary_df_sindy,
    type_1_method_list = c("alasso"),
    type_1_method_cpu_number = 20,
    type_2_method_list = c("bayesian-argos", "bayesian-alasso-ro"),
    type_2_method_cpu_number = 4,
    type_3_method_list = c("pysindy"),
    type_3_method_cpu_number = 1
)
head(sindy_running_time_table)

          n_running_id run_time    eta method
pysindy.1 2-1          0.156013966 2   pysindy
pysindy.2 2-10         0.156255484 2   pysindy
pysindy.3 2-100        0.009609699 2   pysindy
pysindy.4 2-11         0.152208328 2   pysindy
pysindy.5 2-12         0.152150154 2   pysindy
pysindy.6 2-13         0.009924412 2   pysindy

In [11]:
total_running_time_table <- rbind(
    methods_running_time_table,
    sindy_running_time_table
)
total_running_time_table <- rename_method_names(total_running_time_table)
tail(total_running_time_table)

             n_running_id run_time  eta method
pysindy.3095 5-94         0.5819693 5   SINDy
pysindy.3096 5-95         0.7018843 5   SINDy
pysindy.3097 5-96         0.6775393 5   SINDy
pysindy.3098 5-97         0.4772859 5   SINDy
pysindy.3099 5-98         0.4652846 5   SINDy
pysindy.3100 5-99         0.4642460 5   SINDy

## Plot the total computational plot

In [12]:
selected_eta_list <- seq(3, 5, by = 0.5)
methods_running_time_table <- total_running_time_table %>%
  dplyr::filter(eta %in% selected_eta_list)


methods_running_time_table_argos <- methods_running_time_table %>%
  dplyr::filter(method == "ARGOS")
methods_running_time_table_argos$eta <- as.numeric(
  methods_running_time_table_argos$eta
) *
  2 -
  5

methods_running_time_table_bayesian_argos <- methods_running_time_table %>%
  dplyr::filter(method == "Bayesian-ARGOS")
methods_running_time_table_bayesian_argos$eta <- as.numeric(
  methods_running_time_table_bayesian_argos$eta
) *
  2 -
  5

methods_running_time_table_sindy <- methods_running_time_table %>%
  dplyr::filter(method == "SINDy")
methods_running_time_table_sindy$eta <- as.numeric(
  methods_running_time_table_sindy$eta
) *
  2 -
  5

In [ ]:
# - Runtime against n for Lorenz: box plots over the trials at each n, with a
#   dashed quadratic fit of log10 time per method; drawn with the house theme
#   (ResultsAnalysis/plot-style/house_style.R): method colours and legend order
#   Bayesian-ARGOS, ARGOS, SINDy, no legend title (standard 4.7, decision D8),
#   tag and title per 4.8. Content as in the submitted figure.
print(with(methods_running_time_table, table(method, eta)))   # trials per box, for the caption

x_labels <- c(expression(10^3), expression(10^3.5), expression(10^4), expression(10^4.5), expression(10^5))
breaks_log10 <- function(x) 10^seq.int(floor(log10(min(x))), ceiling(log10(max(x))))

runtime_ggplot <-
    ggplot() +
    geom_boxplot(
        data = methods_running_time_table,
        aes(x = eta, y = run_time, fill = method),
        lwd = 0.3
    ) +
    geom_smooth(
        data = methods_running_time_table_argos,
        aes(x = eta - 0.2, y = run_time),
        method = "lm", formula = y ~ stats::poly(x, 2, raw = TRUE),
        alpha = 0.2, lty = 2, color = HOUSE_COLOURS[["ARGOS"]], se = FALSE
    ) +
    geom_smooth(
        data = methods_running_time_table_bayesian_argos,
        aes(x = eta, y = run_time),
        method = "lm", formula = y ~ stats::poly(x, 2, raw = TRUE),
        alpha = 0.2, lty = 2, color = HOUSE_COLOURS[["Bayesian-ARGOS"]], se = FALSE
    ) +
    geom_smooth(
        data = methods_running_time_table_sindy,
        aes(x = eta, y = run_time),
        method = "lm", formula = y ~ stats::poly(x, 2, raw = TRUE),
        alpha = 0.2, lty = 2, color = HOUSE_COLOURS[["SINDy"]], se = FALSE
    ) +
    scale_y_log10(
        breaks = breaks_log10,
        labels = trans_format(log10, math_format(10^.x))
    ) +
    scale_x_discrete(drop = FALSE, labels = x_labels) +
    scale_fill_manual(values = HOUSE_COLOURS, breaks = names(HOUSE_COLOURS), name = NULL) +
    labs(x = expression(italic("n")), y = "Time (s)", tag = "a", title = "Lorenz") +
    house_theme(legend = "bottom") +
    guides(fill = guide_legend(nrow = 1))

nbfigsize(width = 9, height = 7)
runtime_ggplot

## Give the computational plot for another method

In [14]:
dynamical_system_name <- "thomas"
experiment_name_list <- list("argos-alasso", "bayesian-alasso-ro")
method_list <- list("argos-alasso", "bayesian-alasso-ro")
function_number <- 3
exp_n <- TRUE
typical_pattern <- "snr49"
num_init <- 100

In [15]:
total_results_summary_df <- enhance_total_results_summary_df(
    root_path = root_path,
    experiment_name_list = experiment_name_list,
    method_list = method_list,
    function_number = function_number,
    num_init = num_init,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern
)
methods_running_time_table <- create_time_complexity_table(
    total_results_summary_df = total_results_summary_df,
    type_1_method_list = c("alasso"),
    type_1_method_cpu_number = 20,
    type_2_method_list = c("bayesian-argos", "bayesian-alasso-ro"),
    type_2_method_cpu_number = 4
)

[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_1_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_1_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_1_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_2_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_2_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_2_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_3_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_3_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/argos-alasso/thomas/results/thomas_3_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_1_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_1_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_1_e4_e5_se100_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_2_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_2_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_2_e4_e5_se100_snr49.RData"
[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_3_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_3_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/thomas/results/thomas_3_e4_e5_se100_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

In [16]:
total_results_summary_df_sindy <- enhance_total_results_summary_df_py(
    root_path = pysindy_path,
    experiment_name_list = c("pysindy"),
    method_list = c("pysindy"),
    num_init = num_init,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern
)
sindy_running_time_table <- create_time_complexity_table_py(
    total_results_summary_df = total_results_summary_df_sindy,
    type_1_method_list = c("alasso"),
    type_1_method_cpu_number = 20,
    type_2_method_list = c("bayesian-argos", "bayesian-alasso-ro"),
    type_2_method_cpu_number = 4,
    type_3_method_list = c("pysindy"),
    type_3_method_cpu_number = 1
)
total_running_time_table <- rbind(
    methods_running_time_table,
    sindy_running_time_table
)
total_running_time_table <- rename_method_names(total_running_time_table)
tail(total_running_time_table)

[1] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Pysindy/exp/thomas/results/thomas_e2_e3_se100_snr49.RData"
[2] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Pysindy/exp/thomas/results/thomas_e3_e4_se100_snr49.RData"
[3] "/Users/yuzhengzhang/Documents-Local/Code-Local/Bayesian-ARGOS/Pysindy/exp/thomas/results/thomas_e4_e5_se100_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

             n_running_id run_time  eta method
pysindy.3095 5-94         0.6380043 5   SINDy
pysindy.3096 5-95         0.5489397 5   SINDy
pysindy.3097 5-96         0.6424873 5   SINDy
pysindy.3098 5-97         0.5711007 5   SINDy
pysindy.3099 5-98         0.5634670 5   SINDy
pysindy.3100 5-99         0.5824413 5   SINDy

In [17]:
selected_eta_list <- seq(3, 5, by = 0.5)
methods_running_time_table <- total_running_time_table %>%
  dplyr::filter(eta %in% selected_eta_list)


methods_running_time_table_argos <- methods_running_time_table %>%
  dplyr::filter(method == "ARGOS")
methods_running_time_table_argos$eta <- as.numeric(
  methods_running_time_table_argos$eta
) *
  2 -
  5

methods_running_time_table_bayesian_argos <- methods_running_time_table %>%
  dplyr::filter(method == "Bayesian-ARGOS")
methods_running_time_table_bayesian_argos$eta <- as.numeric(
  methods_running_time_table_bayesian_argos$eta
) *
  2 -
  5

methods_running_time_table_sindy <- methods_running_time_table %>%
  dplyr::filter(method == "SINDy")
methods_running_time_table_sindy$eta <- as.numeric(
  methods_running_time_table_sindy$eta
) *
  2 -
  5

In [ ]:
# - Runtime against n for Thomas: box plots over the trials at each n, with a
#   dashed quadratic fit of log10 time per method; drawn with the house theme
#   (ResultsAnalysis/plot-style/house_style.R): method colours and legend order
#   Bayesian-ARGOS, ARGOS, SINDy, no legend title (standard 4.7, decision D8),
#   tag and title per 4.8. Content as in the submitted figure.
print(with(methods_running_time_table, table(method, eta)))   # trials per box, for the caption

x_labels <- c(expression(10^3), expression(10^3.5), expression(10^4), expression(10^4.5), expression(10^5))
breaks_log10 <- function(x) 10^seq.int(floor(log10(min(x))), ceiling(log10(max(x))))

runtime_ggplot_2 <-
    ggplot() +
    geom_boxplot(
        data = methods_running_time_table,
        aes(x = eta, y = run_time, fill = method),
        lwd = 0.3
    ) +
    geom_smooth(
        data = methods_running_time_table_argos,
        aes(x = eta - 0.2, y = run_time),
        method = "lm", formula = y ~ stats::poly(x, 2, raw = TRUE),
        alpha = 0.2, lty = 2, color = HOUSE_COLOURS[["ARGOS"]], se = FALSE
    ) +
    geom_smooth(
        data = methods_running_time_table_bayesian_argos,
        aes(x = eta, y = run_time),
        method = "lm", formula = y ~ stats::poly(x, 2, raw = TRUE),
        alpha = 0.2, lty = 2, color = HOUSE_COLOURS[["Bayesian-ARGOS"]], se = FALSE
    ) +
    geom_smooth(
        data = methods_running_time_table_sindy,
        aes(x = eta, y = run_time),
        method = "lm", formula = y ~ stats::poly(x, 2, raw = TRUE),
        alpha = 0.2, lty = 2, color = HOUSE_COLOURS[["SINDy"]], se = FALSE
    ) +
    scale_y_log10(
        breaks = breaks_log10,
        labels = trans_format(log10, math_format(10^.x))
    ) +
    scale_x_discrete(drop = FALSE, labels = x_labels) +
    scale_fill_manual(values = HOUSE_COLOURS, breaks = names(HOUSE_COLOURS), name = NULL) +
    labs(x = expression(italic("n")), y = "Time (s)", tag = "b", title = "Thomas") +
    house_theme(legend = "bottom") +
    guides(fill = guide_legend(nrow = 1))

nbfigsize(width = 9, height = 7)
runtime_ggplot_2

In [ ]:
# - The two panels side by side with one shared legend row below (no legend
#   title), on the k = 2.5 canvas (18 in wide for 183 mm final, aspect 0.42);
#   cairo_pdf embeds the sans-serif face (Nimbus Sans, the Helvetica substitute).
runtime_figure <-
    (runtime_ggplot + runtime_ggplot_2) +
    plot_layout(guides = "collect") &
    theme(legend.position = "bottom")

nbfigsize(width = 18, height = 7.56)
runtime_figure

save_figure(
    runtime_figure,
    "./ResultsAnalysis/computation-time-plots/imgs/runtime_scaling.pdf",
    width_mm = 183, aspect = 0.42, device = cairo_pdf
)