# Comparing the performance of various methods on the forced Duffing oscillator

Forced Duffing (repo unforced Duffing + harmonic forcing): dx1 = x2; dx2 = -x1 - 0.1 x2 - 5 x1^3 + 5 cos(2t)

### Import the required libraries and files

In [1]:
# Load ggplot2 first as it's a core dependency
library(ggplot2)
# Explicitly import ggproto
ggproto <- ggplot2::ggproto
Stat <- ggplot2::Stat

# Then load other visualization packages
library(plot3D)
library(tidyr)
library(tidyverse)
library(scales)
library(latex2exp)
library(cowplot)
library(ggh4x)
library(ggpubr)
library(gridExtra)
library(patchwork)
library(RColorBrewer)
library(stringr)
library(ggplotgui)
library(dplyr)

Warning message:
“no DISPLAY variable so Tk is not available”

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ lubridate 1.9.5     ✔ tibble    3.3.1
✔ purrr     1.2.2

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘scales’

The following object is masked from ‘package:purrr’:

    discard

The following object is masked from ‘package:readr’:

    col_factor

Attaching package: ‘cowplot’

The following object is masked from ‘package:lubridate’:

    stamp

Attaching package: ‘ggpubr’

The following object is masked from ‘package:cowplot’:

    get_legend

Attaching package: ‘gridExtra’

The following object is masked from ‘package:dplyr’:

    combine

Attaching package: ‘patchwork’

The following object is masked from ‘package:cowplot’:

    align_plots

In [2]:
nbfigsize <- function(width, height) {
    options(repr.plot.width = width, repr.plot.height = height, repr.plot.res = 300)
}

In [3]:
setwd(dirname(dirname(getwd())))

In [4]:
source("./MethodsEvaluation/results_processing_for_analysis.R")
source("./Pysindy/utils/pysindy_results_processing_for_analysis.R")
source("./ResultsAnalysis/plot-style/house_style.R")

In [5]:
ggplot_3d_path <- "./R/ggplot2-3d"
load_r <- list.files(ggplot_3d_path, "*.R")
sapply(load_r, function(i) {
    source(paste0(ggplot_3d_path, "/", i))
})

        axes_3D.R
value   function (mapping = aes(group = 1), data = NULL, geom = "path", ,     position = "identity", na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, ,     ...) , {,     layer(stat = Axes3D, data = data, mapping = mapping, geom = geom, ,         position = position, show.legend = FALSE, inherit.aes = inherit.aes, ,         params = list(na.rm = na.rm, ...)), }
visible FALSE
        axis_labs_3D.R
value   function (mapping = aes(group = 1), data = NULL, geom = "text", ,     position = "identity", na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, ,     ...) , {,     layer(stat = AxisLabels3D, data = data, mapping = mapping, ,         geom = geom, position = position, show.legend = FALSE, ,         inherit.aes = inherit.aes, params = list(na.rm = na.rm, ,             ...)), }
visible FALSE
        labs_3D.R
value   function (mapping = aes(group = 1), data = NULL, geom = "text", ,     position = "identity", na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, ,     ...) , {,     layer(stat = Label3D, data = data, mapping = mapping, geom = geom, ,         position = position, show.legend = FALSE, inherit.aes = inherit.aes, ,         params = list(na.rm = na.rm, ...)), }
visible FALSE
        stat_3D.R
value   function (mapping = NULL, data = NULL, geom = "point", position = "identity", ,     na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, ...) , {,     layer(stat = Stat3D, data = data, mapping = mapping, geom = geom, ,         position = position, show.legend = show.legend, inherit.aes = inherit.aes, ,         params = list(na.rm = na.rm, ...)), }
visible FALSE
        stat_wireframe.R
value   function (mapping = NULL, data = NULL, geom = "path", position = "identity", ,     na.rm = FALSE, show.legend = NA, inherit.aes = TRUE, ...) , {,     layer(stat = StatWireframe, data = data, mapping = mapping, ,         geom = geom, position = position, show.legend = show.legend, ,         inherit.aes = inherit.aes, params = list(na.rm = na.rm, ,             ...)), }
visible FALSE

### General parameters settings

In [6]:
dynamical_system_name <- "forced-duffing"
true_terms_1 <- list("x2")
true_terms_2 <- list("x1", "x2", "x1^3", "cos_2t")
true_terms_3 <- NULL
true_terms_4 <- NULL

### Success rate generation for various number of observations n

#### Load the argos family algorithms results

In [7]:
root_path <- getwd()
experiment_name_list <- list("argos-alasso", "bayesian-alasso-ro")
method_list <- list("argos-alasso", "bayesian-alasso-ro")
function_number <- 2
exp_n <- TRUE
typical_pattern <- "snr49"
num_init <- 100
start <- 2
number_step <- 0.1

In [8]:
total_success_rate_table_n <- generate_total_success_rate_table(
    root_path = root_path,
    experiment_name_list = experiment_name_list,
    method_list = method_list,
    function_number = function_number,
    num_init = num_init,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern,
    true_terms_1 = true_terms_1,
    true_terms_2 = true_terms_2,
    true_terms_3 = true_terms_3,
    true_terms_4 = true_terms_4,
    start = start,
    number_step = number_step
)

tail(total_success_rate_table_n)

[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_1_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_1_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_1_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_2_e2_e3_bo2000_se100_alasso_ridge_snr49.RData"
[2] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_2_e3_e4_bo2000_se100_alasso_ridge_snr49.RData"
[3] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_2_e4_e5_bo2000_se100_alasso_ridge_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_1_e2_e3_se100_snr49.RData"
[2] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_1_e3_e4_se100_snr49.RData"
[3] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_1_e4_e5_se100_snr49.RData"
[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_2_e2_e3_se100_snr49.RData"
[2] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_2_e3_e4_se100_snr49.RData"
[3] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_2_e4_e5_se100_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

   eta Condition Value Model
57 4.5 Correct   0.99  bayesian-alasso-ro
58 4.6 Correct   0.98  bayesian-alasso-ro
59 4.7 Correct   0.97  bayesian-alasso-ro
60 4.8 Correct   0.95  bayesian-alasso-ro
61 4.9 Correct   0.94  bayesian-alasso-ro
62 5.0 Correct   0.92  bayesian-alasso-ro

#### Load the pysindy algorithm results

In [9]:
pysindy_path <- file.path(getwd(), "Pysindy")

In [10]:
# Pysindy runs as SINDYc with control input u = cos(2t); the control feature
# is named "u0" and the PolynomialLibrary expands over [x0, x1, u0], so the
# library also contains u0 cross-terms (56 features total).
true_terms_1_py <- list("x1")
true_terms_2_py <- list("x0", "x1", "x0^3", "u0")
true_terms_3_py <- NULL
true_terms_4_py <- NULL

In [11]:
dynamics_identification_results_n <- check_dynamical_system_py(
    root_path = pysindy_path,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern,
    true_terms_1 = true_terms_1_py,
    true_terms_2 = true_terms_2_py,
    true_terms_3 = true_terms_3_py,
    true_terms_4 = true_terms_4_py,
    function_number = function_number
)

[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Pysindy/exp/forced-duffing/results/forced-duffing_e2_e3_se100_snr49.RData"
[2] "/home/yuzhengz/Projects/Bayesian-ARGOS/Pysindy/exp/forced-duffing/results/forced-duffing_e3_e4_se100_snr49.RData"
[3] "/home/yuzhengz/Projects/Bayesian-ARGOS/Pysindy/exp/forced-duffing/results/forced-duffing_e4_e5_se100_snr49.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

In [12]:
pysindy_success_rate_table_n <- build_successful_rate_table_py(
    dynamics_identification_results = dynamics_identification_results_n,
    num_init = num_init,
    exp_n = exp_n,
    start = start,
    number_step = number_step,
    method = "pysindy"
)

In [13]:
total_success_rate_table_n <- rbind(total_success_rate_table_n, pysindy_success_rate_table_n)
total_success_rate_table_n <- rename_model_names(total_success_rate_table_n)
tail(total_success_rate_table_n)

   eta Condition Value Model
88 4.5 Correct   0.11  SINDy
89 4.6 Correct   0.15  SINDy
90 4.7 Correct   0.18  SINDy
91 4.8 Correct   0.19  SINDy
92 4.9 Correct   0.13  SINDy
93 5.0 Correct   0.23  SINDy

#### Plot the success rate for various n

##### General Plot settings for success rate

In [ ]:
# - Plot style: the shared house theme (ResultsAnalysis/plot-style/house_style.R,
#   sourced above) replaces the former local ggplot_theme0/1 and
#   create_separators(); specification: reply-to-reviewers/Notes/plotting-standard.md.
#   Rows are authored on a canvas HOUSE_K = 2.5 times their final size (rule 4.2.3),
#   so that at final size titles, axis titles and legend text are 7 pt and tick
#   labels 6.5 pt.
# Final width of the two-panel row: the full 183 mm figure width (no attractor column).
row_width_mm <- 183
row_aspect <- 0.30    # row height / row width
house_row_dir <- "./ResultsAnalysis/success-rate-plots/imgs/house"

In [ ]:
# - Success rate against n at SNR = 49 dB: points only (standard 4.6.1), the
#   0.8 reference line with its band (4.10), colours and marker shapes from the
#   house style (4.5, 4.6), panel title per 4.8.2.
total_correct <- total_success_rate_table_n

prob_increase_n <-
    ggplot(total_correct, aes(x = eta, y = Value, colour = Model, fill = Model, shape = Model)) +
    success_rate_layers() +
    geom_point(size = HOUSE_POINT) +
    scale_x_log_n() +
    scale_y_success() +
    method_scales() +
    labs(title = "SNR = 49 dB") +
    house_theme() +
    coord_cartesian(clip = "off")

nbfigsize(width = 8, height = 6)
prob_increase_n

### Success rate generation for various snr values

In [16]:
experiment_name_list <- list("argos-alasso", "bayesian-alasso-ro")
method_list <- list("argos-alasso", "bayesian-alasso-ro")
function_number <- 2
exp_n <- FALSE
typical_pattern <- "n5000"
num_init <- 100
start <- 1
number_step <- 1

# - Generate the total success rate table
total_success_rate_table_snr <- generate_total_success_rate_table(
    root_path = root_path,
    experiment_name_list = experiment_name_list,
    method_list = method_list,
    function_number = function_number,
    num_init = num_init,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern,
    true_terms_1 = true_terms_1,
    true_terms_2 = true_terms_2,
    true_terms_3 = true_terms_3,
    true_terms_4 = NULL,
    start = start,
    number_step = number_step
)

tail(total_success_rate_table_snr)

[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_1_snr1_snr61_bo2000_se100_alasso_ridge_n5000.RData"
[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/argos-alasso/forced-duffing/results/forced-duffing_2_snr1_snr61_bo2000_se100_alasso_ridge_n5000.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 32
[1] 100
[1] 33
[1] 100
[1] 34
[1] 100
[1] 35
[1] 100
[1] 36
[1] 100
[1] 37
[1] 100
[1] 38
[1] 100
[1] 39
[1] 100
[1] 40
[1] 100
[1] 41
[1] 100
[1] 42
[1] 100
[1] 43
[1] 100
[1] 44
[1] 100
[1] 45
[1] 100
[1] 46
[1] 100
[1] 47
[1] 100
[1] 48
[1] 100
[1] 49
[1] 100
[1] 50
[1] 100
[1] 51
[1] 100
[1] 52
[1] 100
[1] 53
[1] 100
[1] 54
[1] 100
[1] 55
[1] 100
[1] 56
[1] 100
[1] 57
[1] 100
[1] 58
[1] 100
[1] 59
[1] 100
[1] 60
[1] 100
[1] 61
[1] 100
[1] 62
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 32
[1] 100
[1] 33
[1] 100
[1] 34
[1] 100
[1] 35
[1] 100
[1] 36
[1] 100
[1] 37
[1] 100
[1] 38
[1] 100
[1] 39
[1] 100
[1] 40
[1] 100
[1] 41
[1] 100
[1] 42
[1] 100
[1] 43
[1] 100
[1] 44
[1] 100
[1] 45
[1] 100
[1] 46
[1] 100
[1] 47
[1] 100
[1] 48
[1] 100
[1] 49
[1] 100
[1] 50
[1] 100
[1] 51
[1] 100
[1] 52
[1] 100
[1] 53
[1] 100
[1] 54
[1] 100
[1] 55
[1] 100
[1] 56
[1] 100
[1] 57
[1] 100
[1] 58
[1] 100
[1] 59
[1] 100
[1] 60
[1] 100
[1] 61
[1] 100
[1] 62
[1] 100

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_1_snr1_snr61_se100_n5000.RData"
[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Experiments/bayesian-alasso-ro/forced-duffing/results/forced-duffing_2_snr1_snr61_se100_n5000.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 32
[1] 100
[1] 33
[1] 100
[1] 34
[1] 100
[1] 35
[1] 100
[1] 36
[1] 100
[1] 37
[1] 100
[1] 38
[1] 100
[1] 39
[1] 100
[1] 40
[1] 100
[1] 41
[1] 100
[1] 42
[1] 100
[1] 43
[1] 100
[1] 44
[1] 100
[1] 45
[1] 100
[1] 46
[1] 100
[1] 47
[1] 100
[1] 48
[1] 100
[1] 49
[1] 100
[1] 50
[1] 100
[1] 51
[1] 100
[1] 52
[1] 100
[1] 53
[1] 100
[1] 54
[1] 100
[1] 55
[1] 100
[1] 56
[1] 100
[1] 57
[1] 100
[1] 58
[1] 100
[1] 59
[1] 100
[1] 60
[1] 100
[1] 61
[1] 100
[1] 62
[1] 100
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 32
[1] 100
[1] 33
[1] 100
[1] 34
[1] 100
[1] 35
[1] 100
[1] 36
[1] 100
[1] 37
[1] 100
[1] 38
[1] 100
[1] 39
[1] 100
[1] 40
[1] 100
[1] 41
[1] 100
[1] 42
[1] 100
[1] 43
[1] 100
[1] 44
[1] 100
[1] 45
[1] 100
[1] 46
[1] 100
[1] 47
[1] 100
[1] 48
[1] 100
[1] 49
[1] 100
[1] 50
[1] 100
[1] 51
[1] 100
[1] 52
[1] 100
[1] 53
[1] 100
[1] 54
[1] 100
[1] 55
[1] 100
[1] 56
[1] 100
[1] 57
[1] 100
[1] 58
[1] 100
[1] 59
[1] 100
[1] 60
[1] 100
[1] 61
[1] 100
[1] 62
[1] 100

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

    snr Condition Value Model
119 57  Correct   0.99  bayesian-alasso-ro
120 58  Correct   0.99  bayesian-alasso-ro
121 59  Correct   0.99  bayesian-alasso-ro
122 60  Correct   0.99  bayesian-alasso-ro
123 61  Correct   0.99  bayesian-alasso-ro
124 62  Correct   0.99  bayesian-alasso-ro

In [17]:
dynamics_identification_results_snr <- check_dynamical_system_py(
    root_path = pysindy_path,
    dynamical_system_name = dynamical_system_name,
    exp_n = exp_n,
    typical_pattern = typical_pattern,
    true_terms_1 = true_terms_1_py,
    true_terms_2 = true_terms_2_py,
    true_terms_3 = true_terms_3_py,
    true_terms_4 = true_terms_4_py,
    function_number = function_number
)

[1] "/home/yuzhengz/Projects/Bayesian-ARGOS/Pysindy/exp/forced-duffing/results/forced-duffing_snr1_snr61_se100_n5000.RData"
[1] 1
[1] 100
[1] 2
[1] 100
[1] 3
[1] 100
[1] 4
[1] 100
[1] 5
[1] 100
[1] 6
[1] 100
[1] 7
[1] 100
[1] 8
[1] 100
[1] 9
[1] 100
[1] 10
[1] 100
[1] 11
[1] 100
[1] 12
[1] 100
[1] 13
[1] 100
[1] 14
[1] 100
[1] 15
[1] 100
[1] 16
[1] 100
[1] 17
[1] 100
[1] 18
[1] 100
[1] 19
[1] 100
[1] 20
[1] 100
[1] 21
[1] 100
[1] 22
[1] 100
[1] 23
[1] 100
[1] 24
[1] 100
[1] 25
[1] 100
[1] 26
[1] 100
[1] 27
[1] 100
[1] 28
[1] 100
[1] 29
[1] 100
[1] 30
[1] 100
[1] 31
[1] 100
[1] 32
[1] 100
[1] 33
[1] 100
[1] 34
[1] 100
[1] 35
[1] 100
[1] 36
[1] 100
[1] 37
[1] 100
[1] 38
[1] 100
[1] 39
[1] 100
[1] 40
[1] 100
[1] 41
[1] 100
[1] 42
[1] 100
[1] 43
[1] 100
[1] 44
[1] 100
[1] 45
[1] 100
[1] 46
[1] 100
[1] 47
[1] 100
[1] 48
[1] 100
[1] 49
[1] 100
[1] 50
[1] 100
[1] 51
[1] 100
[1] 52
[1] 100
[1] 53
[1] 100
[1] 54
[1] 100
[1] 55
[1] 100
[1] 56
[1] 100
[1] 57
[1] 100
[1] 58
[1] 100
[1] 59
[1] 100
[1] 60
[1] 100
[1] 61
[1] 100
[1] 62
[1] 100

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

Warning message in FUN(newX[, i], ...):
“coercing argument of type 'list' to logical”

In [18]:
pysindy_success_rate_table_snr <- build_successful_rate_table_py(
    dynamics_identification_results = dynamics_identification_results_snr,
    num_init = num_init,
    exp_n = exp_n,
    start = start,
    number_step = number_step,
    method = "pysindy"
)

head(pysindy_success_rate_table_snr)

  snr Condition Value Model
1 1   Correct   0     pysindy
2 2   Correct   0     pysindy
3 3   Correct   0     pysindy
4 4   Correct   0     pysindy
5 5   Correct   0     pysindy
6 6   Correct   0     pysindy

In [19]:
total_success_rate_table_snr <- rbind(total_success_rate_table_snr, pysindy_success_rate_table_snr)
total_success_rate_table_snr <- rename_model_names(total_success_rate_table_snr)
tail(total_success_rate_table_snr)

    snr Condition Value Model
181 57  Correct   0.32  SINDy
182 58  Correct   0.32  SINDy
183 59  Correct   0.32  SINDy
184 60  Correct   0.33  SINDy
185 61  Correct   0.33  SINDy
186 62  Correct   0.01  SINDy

#### Plot the success rate based on various snr

In [ ]:
# - Success rate against SNR at n = 5000. The stored table indexes the
#   noiseless case as snr = 62; it is drawn at INF_X beyond the axis break
#   (snr_axis(), standard 4.4). The axis starts at 6 dB, so the grid points at
#   1 to 5 dB lie left of the axis and are not drawn.
total_correct <- total_success_rate_table_snr
total_correct$snr[total_correct$snr == 62] <- Inf
total_correct$x <- snr_x(total_correct$snr)

prob_increase_snr <-
    ggplot(subset(total_correct, x >= 6), aes(x = x, y = Value, colour = Model, fill = Model, shape = Model)) +
    success_rate_layers() +
    geom_point(size = HOUSE_POINT) +
    scale_y_success() +
    method_scales() +
    labs(title = expression(italic("n") * " = 5000")) +
    house_theme(legend = "bottom") +
    guides(colour = guide_legend(nrow = 1), fill = guide_legend(nrow = 1), shape = guide_legend(nrow = 1))
prob_increase_snr <- snr_axis(prob_increase_snr, y_break = 0, extra_y = 0.05)

nbfigsize(width = 8, height = 6)
prob_increase_snr

In [ ]:
# - The two-panel row without a legend, for the composite figure built by
#   Organise-Plots/success-rate-plots/compose_benchmark_figures.sh, and the
#   shared legend of the figure family (one file, identical from every notebook
#   of the family). Canvas: row_width_mm * HOUSE_K / 25.4 in wide, aspect
#   row_aspect; the composite includes it at scale 1 / HOUSE_K, so the text is
#   7 pt final. cairo_pdf embeds the sans-serif face (Nimbus Sans, the Helvetica
#   substitute), the infinity sign included.
row_margin <- theme(plot.margin = margin(t = 0.15, r = 0.2, b = 0.15, l = 0.15, unit = "in"))
success_rate_row <-
    (prob_increase_n + row_margin) +
    (prob_increase_snr + theme(legend.position = "none") + row_margin)

nbfigsize(width = row_width_mm / 25.4 * HOUSE_K, height = row_width_mm / 25.4 * HOUSE_K * row_aspect)
success_rate_row

save_figure(
    success_rate_row,
    file.path(house_row_dir, sprintf("%s_success_rate_row.pdf", dynamical_system_name)),
    width_mm = row_width_mm, aspect = row_aspect, device = cairo_pdf
)
save_legend(cowplot::get_legend(prob_increase_snr), file.path(house_row_dir, "legend_methods.pdf"))

# - Rows below the top row of the composite carry no column titles (standard
#   4.8.2, titles once per column); a blank title keeps the panel geometry
#   identical to the titled row.
blank_title <- labs(title = " ")
success_rate_row_notitle <-
    (prob_increase_n + row_margin + blank_title) +
    (prob_increase_snr + theme(legend.position = "none") + row_margin + blank_title)
save_figure(
    success_rate_row_notitle,
    file.path(house_row_dir, sprintf("%s_success_rate_row_notitle.pdf", dynamical_system_name)),
    width_mm = row_width_mm, aspect = row_aspect, device = cairo_pdf
)